[tool.uv.sources]
XAISuite = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
'Linux'" }]
TPOT = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }, { index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
TTS = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }, { index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
TorchCRF = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }, { index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
TotalSegmentator = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
UtilsRL = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }, { index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
WhisperSpeech = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
XAISuite = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
